version: 2
updates:
- package-ecosystem: npm
  directory: "/Client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/Server"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/Client.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/Server.Tests"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
