version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
- package-ecosystem: npm
  directory: "/Gatekeeper.Client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: nuget
  directory: "/Gatekeeper.Server.Web"
  schedule:	
    interval: daily	
  open-pull-requests-limit: 10	
- package-ecosystem: nuget	
  directory: "/Gatekeeper.Client.Tests"	
  schedule:	
    interval: daily	
  open-pull-requests-limit: 10	
- package-ecosystem: nuget	
  directory: "/Gatekeeper.Server.Web.Tests"
  schedule:	
    interval: daily	
  open-pull-requests-limit: 10	
- package-ecosystem: nuget	
  directory: "/Gatekeeper.Server.Ldap"
  schedule:	
    interval: daily	
  open-pull-requests-limit: 10	
- package-ecosystem: nuget	
  directory: "/Authentick.DotnetSaml.Tests"
  schedule:	
    interval: daily	
  open-pull-requests-limit: 10
