blank_issues_enabled: false
contact_links:
  - name: Community Chat
    url: https://getgatekeeper.zulipchat.com/
    about: Join the Community Chat.
  - name: Feature Requests
    url: https://github.com/GetGatekeeper/Server/discussions/categories/ideas
    about: Please open feature requests as a discussion.
