version: '3'
services:
  authserverdev:
      image: ghcr.io/lukasreschke/authserver-dev:sha-4d1b883
      volumes:
        - .:/workspace:cached
        - /var/run/docker.sock:/var/run/docker-host.sock
      command: /bin/sh -c "while sleep 1000; do :; done"
      depends_on:
        - db
      ports:
        - 1025:1025
        - 8080:8080
        - 8025:8025
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      ports:
        - 5432:5432
  adminer:
      image: adminer
      restart: always
      network_mode: service:authserverdev
      depends_on:
        - db
  mailhog:
      image: mailhog/mailhog
      restart: always
      network_mode: service:authserverdev
