version: '3'
services:
  authserverdev:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
        - .:/workspace:cached
        - /var/run/docker.sock:/var/run/docker-host.sock
      command: /bin/sh -c "while sleep 1000; do :; done"
      depends_on:
        - db
      ports:
        - 8080:8080
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      ports:
        - 5432:5432
  adminer:
      image: adminer
      restart: always
      network_mode: service:authserverdev
      depends_on:
        - db
