version: '3'
services:
  authserverdev:
      image: ghcr.io/authentick/server-dev:sha-ab76378
      volumes:
        - .:/workspace:cached
        - /var/run/docker.sock:/var/run/docker-host.sock
      command: /bin/sh -c "while sleep 1000; do :; done"
      ports:
        - 127.0.0.1:80:80
        - 127.0.0.1:389:389
        - 127.0.0.1:443:443
        - 127.0.0.1:1025:1025
        - 127.0.0.1:8080:8080
        - 127.0.0.1:8025:8025
  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: example
      network_mode: service:authserverdev
  adminer:
      image: adminer
      restart: always
      network_mode: service:authserverdev
  mailhog:
      image: mailhog/mailhog
      restart: always
      network_mode: service:authserverdev
