name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0'
    - name: Install dependencies
      run: dotnet restore Gatekeeper.Server.Web/Gatekeeper.Server.Web.csproj 
    - name: Build
      run: dotnet build --configuration Release Gatekeeper.Server.Web/Gatekeeper.Server.Web.csproj
    - name: Test Gatekeeper.Server.Web
      run: dotnet test Gatekeeper.Server.Web.Tests --collect:"XPlat Code Coverage" -r TestResults/ --settings Gatekeeper.Server.Web.Tests/coverlet.runsettings
    - name: Test Gatekeeper.Client
      run: dotnet test Gatekeeper.Client.Tests --collect:"XPlat Code Coverage" -r TestResults/
    - uses: codecov/codecov-action@v1
      with:
        directory: TestResults/
        fail_ci_if_error: true
        verbose: true
    - uses: actions/setup-node@v1
    - name: NPM install
      run: npm install
      working-directory: ./Gatekeeper.Client/
    - name: Install Gulp
      run: npm install --global gulp-cli
    - name: Build CSS
      run: gulp sass
      working-directory: ./Gatekeeper.Client/
    - name: Perform Percy Tests
      run: ./test.sh
      working-directory: ./Gatekeeper.Server.Web.Tests.Visual
      timeout-minutes: 5
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
