name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore Server/AuthServer.Server.csproj 
    - name: Build
      run: dotnet build --configuration Release Server/AuthServer.Server.csproj
    - name: Test
      run: dotnet test Server.Tests --collect:"XPlat Code Coverage"
    - uses: codecov/codecov-action@v1
      with:
        directory: Server.Tests/TestResults/
        fail_ci_if_error: true
        verbose: true

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: example
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

  gulp:

    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: NPM install
      run: npm install
      working-directory: ./Client/
    - name: Install Gulp
      run: npm install --global gulp-cli
    - name: Build CSS
      run: gulp sass
      working-directory: ./Client/
